/**
 * @fileoverview Chat send/receive REST API — `POST /api/chat` and
 * `POST /api/chat/stream`.
 *
 * The chat endpoints for this template: create a thread on first message if
 * needed, persist the user turn, call core-guardian (see
 * `backend/ai/guardian.ts` — every inference routes through the
 * `CORE_GUARDIAN` service binding), persist the assistant reply, and return
 * it. `/stream` does the same but emits Server-Sent Events so the reply can
 * be rendered token by token; it still persists the finished turn server-side.
 *
 * Thread titles are generated by the model on the FIRST assistant reply (see
 * `titleNewThread`) rather than truncating the user's first message, so a
 * thread list reads like a set of topics. Titling is best-effort: a degraded
 * router leaves the placeholder title in place and never fails the turn.
 *
 * There is no Durable Object / Agents SDK broker here; everything is plain
 * D1 reads/writes plus one RPC call.
 *
 * Mount this router at `/api/chat` in `api/index.ts`.
 */

import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { asc, eq } from "drizzle-orm";

import { getDb } from "@/backend/db";
import { chatThreads, chatMessages, selectChatMessageSchema } from "@/backend/db/schema";
import {
  guardianChat,
  guardianStream,
  guardianTitle,
  readGuardianDeltas,
  GuardianError,
  type GuardianMessage,
} from "@/backend/ai/guardian";

const CHAT_SYSTEM_PROMPT =
  "You are a concise, helpful assistant embedded in a project management dashboard template. Keep replies short and to the point.";

/** Placeholder a thread carries until the model has titled it. */
const PLACEHOLDER_TITLE = "New chat";

/** How many recent messages (of either role) to send as context. */
const CONTEXT_TURNS = 20;

const chatBody = z
  .object({
    threadId: z.string().min(1).optional(),
    message: z.string().min(1).max(8000),
    /**
     * Extra system instruction for the calling surface (e.g. the docs-support
     * panel restricting answers to the knowledge base). Appended after the
     * shared system prompt.
     */
    systemPrompt: z.string().max(4000).optional(),
    /** Routing hints passed straight through to core-guardian. */
    importance: z.enum(["low", "medium", "high"]).optional(),
    complexity: z.enum(["low", "medium", "high"]).optional(),
  })
  .openapi("ChatBody");

const chatResponse = z.object({
  threadId: z.string(),
  message: selectChatMessageSchema,
  /** Present when this turn caused the thread to be (re)titled by the model. */
  title: z.string().optional(),
});

const chatErrorSchema = z.object({ error: z.string() });

export const chatRouter = new OpenAPIHono<{ Bindings: Env }>();

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Map a GuardianError onto the plain-language response the UI shows. */
function guardianErrorMessage(err: unknown): { status: 422 | 429 | 502; error: string } {
  if (err instanceof GuardianError) {
    if (err.status === 422) {
      return { status: 422, error: "No model is available inside the budget right now. Try again later." };
    }
    if (err.status === 429) {
      return { status: 429, error: "The AI router is rate-limited right now. Try again in a minute." };
    }
  }
  console.error("chat guardian error:", err);
  return { status: 502, error: "The AI service is temporarily unavailable." };
}

/**
 * Resolve the thread for this turn, persist the user message, and return the
 * context window plus whether the thread is still awaiting its model title.
 */
async function openTurn(
  env: Env,
  bodyThreadId: string | undefined,
  message: string,
  systemPrompt: string | undefined,
) {
  const db = getDb(env);
  const now = new Date();

  let threadId = bodyThreadId;
  let needsTitle = false;

  if (threadId) {
    const [existing] = await db
      .select({ id: chatThreads.id, title: chatThreads.title })
      .from(chatThreads)
      .where(eq(chatThreads.id, threadId))
      .limit(1);
    if (!existing) threadId = undefined;
    else needsTitle = existing.title === PLACEHOLDER_TITLE;
  }

  if (!threadId) {
    const [created] = await db
      .insert(chatThreads)
      .values({ title: PLACEHOLDER_TITLE, createdAt: now, updatedAt: now })
      .returning({ id: chatThreads.id });
    threadId = created!.id;
    needsTitle = true;
  }

  await db.insert(chatMessages).values({ threadId, role: "user", content: message, createdAt: now });

  const history = await db
    .select({ role: chatMessages.role, content: chatMessages.content })
    .from(chatMessages)
    .where(eq(chatMessages.threadId, threadId))
    .orderBy(asc(chatMessages.createdAt));

  const system = systemPrompt ? `${CHAT_SYSTEM_PROMPT}\n\n${systemPrompt}` : CHAT_SYSTEM_PROMPT;
  const messages: GuardianMessage[] = [
    { role: "system", content: system },
    ...history.slice(-CONTEXT_TURNS),
  ];

  return { db, threadId, needsTitle, messages };
}

/**
 * Title a thread from its first user message, if it is still on the
 * placeholder. Returns the new title, or null when titling was skipped or the
 * router was degraded — the caller treats either as "leave it alone".
 */
async function titleNewThread(env: Env, threadId: string, firstUserMessage: string) {
  const title = await guardianTitle(env, firstUserMessage);
  if (!title) return null;
  await getDb(env)
    .update(chatThreads)
    .set({ title, updatedAt: new Date() })
    .where(eq(chatThreads.id, threadId));
  return title;
}

// ---------------------------------------------------------------------------
// POST / — one-shot send/receive
// ---------------------------------------------------------------------------

chatRouter.openapi(
  createRoute({
    method: "post",
    path: "/",
    tags: ["Chat"],
    summary: "Send a chat message; get the assistant's reply",
    operationId: "chatSend",
    request: {
      body: { content: { "application/json": { schema: chatBody } } },
    },
    responses: {
      200: {
        description: "Assistant reply, persisted.",
        content: { "application/json": { schema: chatResponse } },
      },
      422: {
        description: "No model available inside core-guardian's budget right now.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
      429: {
        description: "core-guardian's circuit breaker is open.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
      502: {
        description: "core-guardian call failed for another reason.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
    },
  }),
  async (c) => {
    const { threadId: bodyThreadId, message, systemPrompt, importance, complexity } =
      c.req.valid("json");

    const { db, threadId, needsTitle, messages } = await openTurn(
      c.env,
      bodyThreadId,
      message,
      systemPrompt,
    );

    let result;
    try {
      result = await guardianChat(c.env, {
        task: "chat_reply",
        useCase: "chat",
        importance: importance ?? "low",
        complexity,
        messages,
      });
    } catch (err) {
      const mapped = guardianErrorMessage(err);
      return c.json({ error: mapped.error }, mapped.status);
    }

    const [assistantRow] = await db
      .insert(chatMessages)
      .values({
        threadId,
        role: "assistant",
        content: result.text,
        provider: result.provider,
        model: result.model,
        costUsd: result.costUsd,
      })
      .returning();
    await db.update(chatThreads).set({ updatedAt: new Date() }).where(eq(chatThreads.id, threadId));

    const title = needsTitle ? await titleNewThread(c.env, threadId, message) : null;

    return c.json({ threadId, message: assistantRow!, ...(title ? { title } : {}) }, 200);
  },
);

// ---------------------------------------------------------------------------
// POST /stream — Server-Sent Events
// ---------------------------------------------------------------------------
//
// Hand-registered (not `openapi()`) because the response is `text/event-stream`
// rather than JSON; it is documented in the spec through the block below.

chatRouter.openAPIRegistry.registerPath({
  method: "post",
  path: "/api/chat/stream",
  tags: ["Chat"],
  summary: "Send a chat message; stream the assistant's reply as SSE",
  operationId: "chatStream",
  request: { body: { content: { "application/json": { schema: chatBody } } } },
  responses: {
    200: {
      description:
        "Server-Sent Events. `meta` carries the thread id, `delta` each text chunk, " +
        "`title` the model-generated thread title, `done` the persisted message, `error` a failure.",
      content: { "text/event-stream": { schema: z.string() } },
    },
  },
});

chatRouter.post("/stream", async (c) => {
  const parsed = chatBody.safeParse(await c.req.json().catch(() => ({})));
  if (!parsed.success) return c.json({ error: "Invalid chat request body." }, 400);
  const { threadId: bodyThreadId, message, systemPrompt, importance, complexity } = parsed.data;

  const { db, threadId, needsTitle, messages } = await openTurn(
    c.env,
    bodyThreadId,
    message,
    systemPrompt,
  );

  const encoder = new TextEncoder();
  const send = (controller: ReadableStreamDefaultController, event: string, data: unknown) =>
    controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));

  const stream = new ReadableStream({
    async start(controller) {
      send(controller, "meta", { threadId });

      let text = "";
      try {
        const upstream = await guardianStream(c.env, {
          task: "chat_reply",
          useCase: "chat",
          importance: importance ?? "low",
          complexity,
          messages,
        });

        for await (const delta of readGuardianDeltas(upstream)) {
          text += delta;
          send(controller, "delta", { text: delta });
        }
      } catch (err) {
        const mapped = guardianErrorMessage(err);
        send(controller, "error", { error: mapped.error, status: mapped.status });
        controller.close();
        return;
      }

      // An empty completion is a failure the UI must see, not an empty bubble.
      if (!text.trim()) {
        send(controller, "error", { error: "The model returned an empty reply.", status: 502 });
        controller.close();
        return;
      }

      const [assistantRow] = await db
        .insert(chatMessages)
        .values({ threadId, role: "assistant", content: text })
        .returning();
      await db.update(chatThreads).set({ updatedAt: new Date() }).where(eq(chatThreads.id, threadId));

      if (needsTitle) {
        const title = await titleNewThread(c.env, threadId, message);
        if (title) send(controller, "title", { threadId, title });
      }

      send(controller, "done", { threadId, message: assistantRow });
      controller.close();
    },
  });

  return new Response(stream, {
    headers: {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    },
  });
});
