/**
 * @fileoverview Chat send/receive REST API — `POST /api/chat` and
 * `POST /api/chat/stream`.
 *
 * The chat endpoints for this template: create a thread on first message if
 * needed, persist the user turn, call core-guardian (see
 * `backend/ai/guardian/` — every inference routes through the
 * `CORE_GUARDIAN` service binding), persist the assistant reply, and return
 * it. `/stream` does the same but emits Server-Sent Events so the reply can
 * be rendered token by token; it still persists the finished turn server-side.
 *
 * Thread titles are generated by the model on the FIRST assistant reply (see
 * `titleNewThread`) rather than truncating the user's first message, so a
 * thread list reads like a set of topics. Titling is best-effort: a degraded
 * router leaves the placeholder title in place and never fails the turn.
 *
 * There is no Durable Object / Agents SDK broker here; everything is plain
 * D1 reads/writes plus one RPC call.
 *
 * Mount this router at `/api/chat` in `api/index.ts`.
 */

import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";
import { asc, eq } from "drizzle-orm";

import { getDb } from "@/backend/db";
import { chatThreads, chatMessages, selectChatMessageSchema } from "@/backend/db/schema";
import {
  GUARDIAN_TASKS,
  GuardianConfigError,
  GuardianError,
  ROUTING_PROFILE_NAMES,
  resolveProfile,
  guardianChat,
  guardianStream,
  guardianStreamMeta,
  guardianTitle,
  readGuardianStream,
  type GuardianMessage,
  type GuardianUsage,
} from "@/backend/ai/guardian";

const CHAT_SYSTEM_PROMPT =
  "You are a concise, helpful assistant embedded in a project management dashboard template. Keep replies short and to the point.";

/** Placeholder a thread carries until the model has titled it. */
const PLACEHOLDER_TITLE = "New chat";

/** How many recent messages (of either role) to send as context. */
const CONTEXT_TURNS = 20;

const chatBody = z
  .object({
    threadId: z.string().min(1).optional(),
    message: z.string().min(1).max(8000),
    /**
     * Extra system instruction for the calling surface (e.g. the docs-support
     * panel restricting answers to the knowledge base). Appended after the
     * shared system prompt.
     */
    systemPrompt: z.string().max(4000).optional(),
    /**
     * Which routing profile to run this turn under.
     *
     * A closed set of names, NOT raw routing dials: the server owns the
     * mapping (see `resolveProfile`), so an unauthenticated caller cannot
     * invent hint combinations the router was never designed for, and the
     * profile definition lives in one place rather than in every client.
     */
    profile: z.enum(ROUTING_PROFILE_NAMES).optional(),
  })
  .openapi("ChatBody");

const chatResponse = z.object({
  threadId: z.string(),
  message: selectChatMessageSchema,
  /** Present when this turn caused the thread to be (re)titled by the model. */
  title: z.string().optional(),
});

const chatErrorSchema = z.object({ error: z.string() });

export const chatRouter = new OpenAPIHono<{ Bindings: Env }>();

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Map a failed run onto the plain-language response the UI shows. */
function guardianErrorMessage(err: unknown): { status: 422 | 429 | 500 | 502; error: string } {
  // A misconfigured Worker is NOT a transient AI outage, and saying "try again"
  // about it would send someone away to wait for a fix that is never coming.
  // Surface the real message: it names the var and the script that sets it,
  // and carries no secret.
  if (err instanceof GuardianConfigError) {
    console.error("chat guardian config error:", err.message);
    return { status: 500, error: err.message };
  }
  if (err instanceof GuardianError) {
    if (err.status === 422) {
      return { status: 422, error: "No model is available inside the budget right now. Try again later." };
    }
    if (err.status === 429) {
      return { status: 429, error: "The AI router is rate-limited right now. Try again in a minute." };
    }
  }
  console.error("chat guardian error:", err);
  return { status: 502, error: "The AI service is temporarily unavailable." };
}

/**
 * Resolve the thread for this turn, persist the user message, and return the
 * context window plus whether the thread is still awaiting its model title.
 */
async function openTurn(
  env: Env,
  bodyThreadId: string | undefined,
  message: string,
  systemPrompt: string | undefined,
) {
  const db = getDb(env);
  const now = new Date();

  let threadId = bodyThreadId;
  let needsTitle = false;

  if (threadId) {
    const [existing] = await db
      .select({ id: chatThreads.id, titled: chatThreads.titled })
      .from(chatThreads)
      .where(eq(chatThreads.id, threadId))
      .limit(1);
    if (!existing) threadId = undefined;
    else needsTitle = !existing.titled;
  }

  if (!threadId) {
    const [created] = await db
      .insert(chatThreads)
      .values({ title: PLACEHOLDER_TITLE, createdAt: now, updatedAt: now })
      .returning({ id: chatThreads.id });
    threadId = created!.id;
    needsTitle = true;
  }

  await db.insert(chatMessages).values({ threadId, role: "user", content: message, createdAt: now });

  const history = await db
    .select({ role: chatMessages.role, content: chatMessages.content })
    .from(chatMessages)
    .where(eq(chatMessages.threadId, threadId))
    .orderBy(asc(chatMessages.createdAt));

  const system = systemPrompt ? `${CHAT_SYSTEM_PROMPT}\n\n${systemPrompt}` : CHAT_SYSTEM_PROMPT;
  const messages: GuardianMessage[] = [
    { role: "system", content: system },
    ...history.slice(-CONTEXT_TURNS),
  ];

  return { db, threadId, needsTitle, messages };
}

/**
 * Title a thread from its first user message, if it is still on the
 * placeholder. Returns the new title, or null when titling was skipped or the
 * router was degraded — the caller treats either as "leave it alone".
 */
async function titleNewThread(env: Env, threadId: string, firstUserMessage: string) {
  const title = await guardianTitle(env, firstUserMessage);
  if (!title) return null;
  await getDb(env)
    .update(chatThreads)
    .set({ title, titled: true, updatedAt: new Date() })
    .where(eq(chatThreads.id, threadId));
  return title;
}

// ---------------------------------------------------------------------------
// POST / — one-shot send/receive
// ---------------------------------------------------------------------------

chatRouter.openapi(
  createRoute({
    method: "post",
    path: "/",
    tags: ["Chat"],
    summary: "Send a chat message; get the assistant's reply",
    operationId: "chatSend",
    request: {
      body: { content: { "application/json": { schema: chatBody } } },
    },
    responses: {
      200: {
        description: "Assistant reply, persisted.",
        content: { "application/json": { schema: chatResponse } },
      },
      422: {
        description: "No model available inside core-guardian's budget right now.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
      500: {
        description:
          "This Worker is misconfigured — GUARDIAN_PROJECT is unset, so no run can be " +
          "attributed. Reported separately from 502 because retrying will not help.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
      429: {
        description: "core-guardian's circuit breaker is open.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
      502: {
        description: "core-guardian call failed for another reason.",
        content: { "application/json": { schema: chatErrorSchema } },
      },
    },
  }),
  async (c) => {
    const { threadId: bodyThreadId, message, systemPrompt, profile } = c.req.valid("json");
    const routing = resolveProfile(profile);

    const { db, threadId, needsTitle, messages } = await openTurn(
      c.env,
      bodyThreadId,
      message,
      systemPrompt,
    );

    const startedAt = Date.now();
    let result;
    try {
      result = await guardianChat(c.env, {
        task: GUARDIAN_TASKS.chatReply,
        ...routing,
        messages,
      });
    } catch (err) {
      const mapped = guardianErrorMessage(err);
      return c.json({ error: mapped.error }, mapped.status);
    }

    const [assistantRow] = await db
      .insert(chatMessages)
      .values({
        threadId,
        role: "assistant",
        content: result.text,
        provider: result.provider,
        model: result.model,
        costUsd: result.costUsd,
        latencyMs: Date.now() - startedAt,
      })
      .returning();
    await db.update(chatThreads).set({ updatedAt: new Date() }).where(eq(chatThreads.id, threadId));

    const title = needsTitle ? await titleNewThread(c.env, threadId, message) : null;

    return c.json({ threadId, message: assistantRow!, ...(title ? { title } : {}) }, 200);
  },
);

// ---------------------------------------------------------------------------
// POST /stream — Server-Sent Events
// ---------------------------------------------------------------------------
//
// Hand-registered (not `openapi()`) because the response is `text/event-stream`
// rather than JSON; it is documented in the spec through the block below.

chatRouter.openAPIRegistry.registerPath({
  method: "post",
  path: "/api/chat/stream",
  tags: ["Chat"],
  summary: "Send a chat message; stream the assistant's reply as SSE",
  operationId: "chatStream",
  request: { body: { content: { "application/json": { schema: chatBody } } } },
  responses: {
    200: {
      description:
        "Server-Sent Events. `meta` carries the thread id; `routed` the provider/model core-guardian " +
        "chose; `delta` each chunk of the answer; `reasoning` each chunk of the model's thinking " +
        "(never part of the answer); `usage` the final token counts; `title` the model-generated " +
        "thread title; `done` the persisted message plus latency; `error` a failure.",
      content: { "text/event-stream": { schema: z.string() } },
    },
  },
});

chatRouter.post("/stream", async (c) => {
  const parsed = chatBody.safeParse(await c.req.json().catch(() => ({})));
  if (!parsed.success) return c.json({ error: "Invalid chat request body." }, 400);
  const { threadId: bodyThreadId, message, systemPrompt, profile } = parsed.data;
  const routing = resolveProfile(profile);

  const { db, threadId, needsTitle, messages } = await openTurn(
    c.env,
    bodyThreadId,
    message,
    systemPrompt,
  );

  const encoder = new TextEncoder();

  /**
   * Write one SSE frame, or report that the client has gone.
   *
   * A browser that aborts mid-reply (the Stop button, a navigation) leaves the
   * controller closed, and `enqueue` then throws. Letting that throw escape
   * took the whole `start()` down — including the writes that persist the turn
   * — and, worse, the catch block's own error frame threw a second time. So
   * this reports failure instead of throwing, and callers stop writing.
   *
   * @returns false once the client is no longer listening.
   */
  const send = (controller: ReadableStreamDefaultController, event: string, data: unknown): boolean => {
    try {
      controller.enqueue(encoder.encode(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`));
      return true;
    } catch {
      return false;
    }
  };

  /** Close the controller, tolerating a client that already disconnected. */
  const close = (controller: ReadableStreamDefaultController) => {
    try {
      controller.close();
    } catch {
      // Already closed by the disconnect. Nothing to do.
    }
  };

  const startedAt = Date.now();

  // The controller is captured here rather than the work being done inside
  // `start()`. When the browser disconnects the runtime cancels the stream and
  // stops running its body, which is how an aborted reply used to be thrown
  // away entirely: the tokens were generated and paid for, and nothing was
  // written. Driving the turn from a promise handed to `waitUntil` instead
  // means the persist finishes whether or not anyone is still reading.
  let controller!: ReadableStreamDefaultController;
  const stream = new ReadableStream({
    start(c) {
      controller = c;
    },
  });

  const turn = (async () => {
    send(controller, "meta", { threadId });

    let text = "";
    let reasoning = "";
    let usage: GuardianUsage | null = null;
    let provider: string | null = null;
    let model: string | null = null;
    /** Set once the reader has gone, so we stop generating rather than bill for nobody. */
    let disconnected = false;

    try {
      const upstream = await guardianStream(c.env, {
        task: GUARDIAN_TASKS.chatReply,
        ...routing,
        messages,
      });

      // The router reports its decision in headers, before the first token,
      // so the UI can name the real model while the answer is still coming.
      const routed = guardianStreamMeta(upstream);
      provider = routed.provider;
      model = routed.model;
      send(controller, "routed", { provider, model, requestUuid: routed.requestUuid });

      for await (const event of readGuardianStream(upstream)) {
        if (event.type === "delta") {
          text += event.text;
          // A closed controller means the reader is gone. Stop generating, and
          // fall through to the persist below so the thread owns the tokens
          // that were already produced.
          if (!send(controller, "delta", { text: event.text })) {
            disconnected = true;
            break;
          }
        } else if (event.type === "reasoning") {
          // Thinking is NOT the answer. It is streamed separately so a
          // surface can fold it away, and never concatenated into `text`.
          reasoning += event.text;
          send(controller, "reasoning", { text: event.text });
        } else {
          usage = event.usage;
          send(controller, "usage", event.usage);
        }
      }
    } catch (err) {
      const mapped = guardianErrorMessage(err);
      send(controller, "error", { error: mapped.error, status: mapped.status });
      close(controller);
      return;
    }

    // An empty completion is a failure the UI must see, not an empty bubble.
    // A reasoning model that spent every token thinking lands here too, so
    // say which of the two happened rather than a generic failure.
    if (!text.trim()) {
      send(controller, "error", {
        error: reasoning.trim()
          ? "The model spent its whole reply reasoning and produced no answer. Try again."
          : "The model returned an empty reply.",
        status: 502,
      });
      close(controller);
      return;
    }

    const [assistantRow] = await db
      .insert(chatMessages)
      .values({
        threadId,
        role: "assistant",
        content: text,
        provider,
        model,
        latencyMs: Date.now() - startedAt,
        // Null, not 0, when the provider reported nothing: a measured zero and
        // "not reported" are different facts and the receipt renders them
        // differently.
        promptTokens: usage?.promptTokens ?? null,
        completionTokens: usage?.completionTokens ?? null,
      })
      .returning();
    await db.update(chatThreads).set({ updatedAt: new Date() }).where(eq(chatThreads.id, threadId));

    // Titling costs a model call. Skip it for a reply nobody waited for; the
    // next turn on this thread will title it, because `titled` is still false.
    if (needsTitle && !disconnected) {
      const title = await titleNewThread(c.env, threadId, message);
      if (title) send(controller, "title", { threadId, title });
    }

    send(controller, "done", {
      threadId,
      message: assistantRow,
      latencyMs: Date.now() - startedAt,
      usage,
    });
    close(controller);
  })();

  // Survives the client hanging up, so the persist above always runs.
  c.executionCtx.waitUntil(turn);

  return new Response(stream, {
    headers: {
      "content-type": "text/event-stream; charset=utf-8",
      "cache-control": "no-cache, no-transform",
      connection: "keep-alive",
    },
  });
});
