/**
 * @fileoverview NotebookLM consultation tool — the shared core that all
 * NotebookLM-related agents and API routes delegate to.
 *
 * Flow:
 *  1. Build an authenticated `NotebookLMClient` using cookies + CSRF token.
 *  2. Read `agent_rules` from the `global_config` D1 table.
 *  3. Prepend the rules to the user's query so NotebookLM always follows
 *     the configured behavioral constraints.
 *  4. Call `client.chat.ask(notebookId, guardedQuery)` and return the result.
 *
 * Credential layout (two storage tiers):
 *  - `NOTEBOOKLM_COOKIES`       → Worker Secret  (session cookies)
 *  - `CAREER_NOTEBOOKLM_ID`     → env var         (notebook identifier)
 *
 * The CSRF token is auto-discovered by `NotebookLMClient.connect()` from
 * the live NotebookLM page using the session cookies.
 */

import { eq } from "drizzle-orm";
import { NotebookLMClient, type AskResult } from "notebooklm-sdk";

import { getDb } from "@/backend/db";
import { globalConfig } from "@/backend/db/schema";
import { getNotebookLMCookies } from "@/backend/utils/secrets";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * The shape returned by {@link consultNotebook} and consumed by both the
 * `/api/notebook/chat` route and the `NotebookLMAgent` Durable Object.
 */
export type NotebookConsultation = {
  /** The answer text generated by NotebookLM. */
  answer: string;
  /** Conversation identifier for multi-turn tracking. */
  conversationId: string;
  /** Sequential turn number within the conversation. */
  turnNumber: number;
  /** Source references cited in the answer. */
  references: AskResult["references"];
};

/**
 * Error thrown when NotebookLM session cookies are expired or invalid.
 * The `recoveryCommand` property contains the exact CLI command to fix it.
 */
export class SessionExpiredError extends Error {
  public readonly recoveryCommand: string;

  constructor(cause?: unknown) {
    super("SESSION_EXPIRED: NotebookLM session cookies are expired or invalid.");
    this.name = "SessionExpiredError";
    this.recoveryCommand = "pnpm run session:sync";
    if (cause) this.cause = cause;
  }
}

// ---------------------------------------------------------------------------
// Primary public function
// ---------------------------------------------------------------------------

/**
 * Send a query to the NotebookLM career knowledge base.
 *
 * Agent rules from D1 are prepended to every query so the model always
 * operates within the configured guardrails.
 *
 * @param env - Cloudflare Worker environment bindings.
 * @param query - Natural-language question from the user or an agent.
 * @returns A {@link NotebookConsultation} with the answer, conversation context,
 *          and source references.
 * @throws {SessionExpiredError} if the SDK fails due to expired session cookies.
 */
export async function consultNotebook(
  env: Env,
  query: string,
): Promise<NotebookConsultation> {
  const [client, notebookId, rules] = await Promise.all([
    createNotebookClient(env),
    env.CAREER_NOTEBOOKLM_ID,
    readAgentRules(env),
  ]);
  const guardedQuery = withAgentRules(query, rules);

  try {
    const result = await client.chat.ask(notebookId, guardedQuery);

    return {
      answer: result.answer,
      conversationId: result.conversationId,
      turnNumber: result.turnNumber,
      references: result.references,
    };
  } catch (error) {
    // Detect auth-related failures and wrap with actionable recovery info
    if (isAuthError(error)) {
      throw new SessionExpiredError(error);
    }
    throw error;
  }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Construct an authenticated {@link NotebookLMClient}.
 *
 * Uses `NotebookLMClient.connect({ cookies })` which:
 *   1. Parses the cookie string into a map
 *   2. Fetches the live NotebookLM page to extract the CSRF token
 *   3. Returns a fully authenticated client
 *
 * This eliminates the need for a separate `NOTEBOOKLM_AUTH_TOKEN` binding —
 * the SDK discovers the CSRF token automatically from the session cookies.
 */
async function createNotebookClient(env: Env): Promise<NotebookLMClient> {
  const cookieString = await getNotebookLMCookies(env);

  if (!cookieString || cookieString.length < 10) {
    throw new Error(
      "NOTEBOOKLM_COOKIES is empty or missing. " +
      "Run: npx wrangler secret put NOTEBOOKLM_COOKIES",
    );
  }

  return NotebookLMClient.connect(
    { cookies: cookieString },
    { timeoutMs: 30_000 },
  );
}

/**
 * Read the `agent_rules` array from the `global_config` D1 table.
 *
 * These rules are editable via the `/config` UI and are prepended to every
 * NotebookLM query to enforce behavioral constraints.
 *
 * @returns An array of rule strings, or an empty array if none are configured.
 */
async function readAgentRules(env: Env): Promise<string[]> {
  const db = getDb(env);
  const [row] = await db
    .select({ value: globalConfig.value })
    .from(globalConfig)
    .where(eq(globalConfig.key, "agent_rules"))
    .limit(1);

  return Array.isArray(row?.value)
    ? row.value.filter((value): value is string => typeof value === "string")
    : [];
}

/**
 * Wrap a user query with agent rules.
 *
 * If rules are configured, they are formatted as a bullet list and prepended
 * to the query.  If no rules exist, the original query is returned unchanged.
 */
function withAgentRules(query: string, rules: string[]): string {
  if (rules.length === 0) {
    return query;
  }

  return `Follow these Career Orchestrator rules before answering:\n${rules.map((rule) => `- ${rule}`).join("\n")}\n\nUser query:\n${query}`;
}

/**
 * Detect whether an error from the NotebookLM SDK indicates expired
 * or invalid session cookies.
 *
 * Checks for:
 *  - SDK `AuthError` class name
 *  - Error messages containing login/auth/expired/CSRF keywords
 *  - Google sign-in redirect indicators
 */
function isAuthError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;

  const err = error as Error;
  const name = err.name?.toLowerCase() ?? "";
  const msg = err.message?.toLowerCase() ?? "";

  if (name.includes("auth")) return true;
  if (msg.includes("expired")) return true;
  if (msg.includes("login")) return true;
  if (msg.includes("csrf")) return true;
  if (msg.includes("sign in")) return true;
  if (msg.includes("accounts.google.com")) return true;
  if (msg.includes("unauthorized")) return true;

  return false;
}

// ---------------------------------------------------------------------------
// Session availability check (used by agent healthProbe and health checks)
// ---------------------------------------------------------------------------

/** Result of a session availability check. */
export type SessionCheckResult = {
  available: boolean;
  source: "kv" | "secret" | "none";
};

/**
 * Lightweight check for whether a valid NotebookLM session exists.
 *
 * Agents and health checks should use this instead of reading KV/secrets
 * directly. The logic mirrors {@link getNotebookLMCookies} priority order:
 *   1. KV `ACTIVE_NOTEBOOKLM_SESSION` (hot-swap, instant rotation)
 *   2. Worker Secret `NOTEBOOKLM_COOKIES` (fallback, requires redeploy)
 *
 * Does NOT validate the session against Google — only checks that a
 * non-trivial cookie string is present.
 */
export async function checkNotebookLMSession(
  env: Env,
): Promise<SessionCheckResult> {
  // Check KV first (hot-swap source)
  try {
    const kvSession = await env.KV.get("ACTIVE_NOTEBOOKLM_SESSION");
    if (kvSession && kvSession.trim().length > 10) {
      return { available: true, source: "kv" };
    }
  } catch {
    // KV read failed — fall through to secret
  }

  // Check Worker Secret fallback
  if (env.NOTEBOOKLM_COOKIES && env.NOTEBOOKLM_COOKIES.trim().length > 10) {
    return { available: true, source: "secret" };
  }

  return { available: false, source: "none" };
}

