import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";

import { roles } from "./roles";

// ---------------------------------------------------------------------------
// Table & column documentation (consumed by /api/docs/schema)
// ---------------------------------------------------------------------------

/** Human-readable description of the `role_analyses` table for the documentation UI. */
export const ROLE_ANALYSES_TABLE_DESCRIPTION =
  "Top-level hireability analysis for a role. Stores overall hire score, compensation comparison, and AI rationale. Generated by the role_analysis task after NotebookLM consultation and gpt-oss-120b structured evaluation.";

/** Per-column descriptions surfaced in the documentation schema viewer. */
export const ROLE_ANALYSES_COLUMN_DESCRIPTIONS: Record<string, string> = {
  id: "UUID primary key, generated at creation.",
  role_id: "Foreign key to the analyzed role. Cascades on delete.",
  version: "Revision number within a role (1 = first analysis, 2 = second, etc.).",
  hire_score:
    "Overall likelihood-to-hire score (0–100). Considers skills match, experience alignment, and culture fit.",
  hire_rationale:
    "AI-generated rationale explaining the hire score, referencing specific evidence from NotebookLM and resume bullets.",
  compensation_score:
    "Score (0–100) comparing the role's salary range against the user's compensation baseline stored in global_config.",
  compensation_rationale:
    "AI-generated rationale explaining the compensation comparison, factoring base, stock, benefits, and bonus.",
  config_notebooklm_prompt: "Snapshot of the NotebookLM prompt template used during this analysis.",
  config_compensation_baseline:
    "Snapshot of the compensation baseline text used during this analysis.",
  config_career_stories:
    "Snapshot of the career stories injected into the scoring prompt during this analysis.",
  used_defaults:
    "1 if any config value fell back to hardcoded defaults because no user-provided value existed in global_config.",
  analyzed_at: "Unix timestamp (seconds) of when this analysis was performed.",
};

// ---------------------------------------------------------------------------
// Table definition
// ---------------------------------------------------------------------------

export const roleAnalyses = sqliteTable(
  "role_analyses",
  {
    id: text("id").primaryKey(),
    roleId: text("role_id")
      .notNull()
      .references(() => roles.id, { onDelete: "cascade" }),
    version: integer("version").notNull().default(1),
    hireScore: integer("hire_score").notNull(),
    hireRationale: text("hire_rationale").notNull(),
    compensationScore: integer("compensation_score").notNull(),
    compensationRationale: text("compensation_rationale").notNull(),
    configNotebooklmPrompt: text("config_notebooklm_prompt"),
    configCompensationBaseline: text("config_compensation_baseline"),
    configCareerStories: text("config_career_stories"),
    usedDefaults: integer("used_defaults", { mode: "boolean" }).default(false),
    analyzedAt: integer("analyzed_at", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    roleIdx: index("role_analyses_role_id_idx").on(table.roleId),
  }),
);

export const insertRoleAnalysisSchema = createInsertSchema(roleAnalyses);
export const selectRoleAnalysisSchema = createSelectSchema(roleAnalyses);
export type RoleAnalysis = typeof roleAnalyses.$inferSelect;
export type NewRoleAnalysis = typeof roleAnalyses.$inferInsert;
